version: "3.9"

services:

  web:
    build: .
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 60 businessinteligence.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=5432
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:

volumes:
  business:
