# Generated by Django 5.0.6 on 2024-06-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mantenimiento',
            table='mantenimiento',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
