# Generated by Django 5.0.6 on 2024-06-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0003_servicio_rename_licenseplate_mantenimiento_vin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='vin',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='serviciomantenimiento',
            old_name='maintenance_id',
            new_name='maintenance',
        ),
        migrations.RenameField(
            model_name='serviciomantenimiento',
            old_name='service_id',
            new_name='service',
        ),
    ]
