# Generated by Django 5.0.6 on 2024-06-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0005_remove_vehicle_id_alter_vehicle_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='cost',
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleDate', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.vehicle')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.cita'),
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.mantenimiento')),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='ServicioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.cita')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_intelligence.servicio')),
            ],
            options={
                'db_table': 'service_appointment',
            },
        ),
        migrations.DeleteModel(
            name='ServicioMantenimiento',
        ),
    ]
