# Generated by Django 5.0.6 on 2024-06-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0006_remove_servicio_cost_cita_mantenimiento_appointment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciocita',
            old_name='cita',
            new_name='appoinment',
        ),
    ]
