# Generated by Django 5.0.6 on 2024-06-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_intelligence', '0007_rename_cita_serviciocita_appoinment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='mantenimiento',
            new_name='maintenance',
        ),
        migrations.RenameField(
            model_name='serviciocita',
            old_name='appoinment',
            new_name='appointment',
        ),
    ]
